### ISSUE TITLE
Ugrade rxdart to 0.23.x

### ISSUE THREAD

**Issue by mateusfccp** [lukepighetti/hydrated#14]
This plugin is breaking my code because of the Observable removal of 0.23.x.

The upgrade can be easily made with [rxdart_codemod](https://github.com/brianegan/rxdart_codemod).

Thanks, in advance.

**Comment by mateusfccp** [comment]
Could you please release a new version after accepting my PR?

**Comment by lukepighetti** [comment]
Hi there, I'm thinking of ending support for this plugin. Would you be interested in taking it over?

**Comment by mateusfccp** [comment]
I actually don't have the time to really take care of it, but I can at least keep it stable, as it's being used in one project at my workplace...

So, if you prefer to transfer it to me, I would gladly accept...

**Comment by lukepighetti** [comment]
I just invited you as a collaborator https://github.com/lukepighetti/hydrated/invitations

If you need me to do anything to allow you to publish to `pub` let me know

**Comment by mateusfccp** [comment]
@lukepighetti When trying to publish I get:

`InsufficientPermissions: Insufficient permissions to upload new versions of package `hydrated`..`
