### ISSUE TITLE
Question: How could I persist a list of a model

### ISSUE THREAD

**Issue by devfelipereis** [lukepighetti/hydrated#8]
Hello, I'm a flutter newbee.

I'm storing a token using this and it's working like a charm. Now I would like to know how to store a list of houses.

I have a list of favorite houses in my bloc. Like this:

```
...
BehaviorSubject<List<House>> _favoritesController = BehaviorSubject<List<House>>(seedValue: <House>[]);
Stream<List<House>> get favorites => _favoritesController.stream;
...
```

Is it possible to persist this list?

Thank you.

**Comment by lukepighetti** [comment]
Hi! Yes it is, you would need to serialize that list of houses. In JavaScript we have JSON.stringify(myObject). In dart, you will have to create a .toJSON() method for your class House and then provide a method to serialize/deserialize a list of houses.

From there you would do something like

```dart
  final count$ = HydratedSubject<List<House>>>(
    "houses",
    hydrate: (value) => _deserializeHouses(value),
    persist: (value) => _serializeHouses(value),
    seedValue: SerializedClass(0),
  );

/// just guessing here
_deserializeHouses(String s)=>jsonDecode(s).map((h)=>House.fromJson(h)).toList();

_serializeHouses(List<House> houses)=>jsonEncode(houses.map((h)=>h.toJson)).toList());
```

**Comment by devfelipereis** [comment]
Thank you so much. It's working!!

I just did with this:

```
final favorites$ = HydratedSubject<List<House>>(
    "favorites",
    hydrate: (String s) => List<House>.from(jsonDecode(s).map((s)=>House.fromJson(s))),
    persist: (List<House> houses) => jsonEncode(houses.map((s)=>s.toJson()).toList()),
    seedValue: List<House>(),
);
```

**Comment by lukepighetti** [comment]
Awesome man, glad it worked for you! And thanks for sharing your final solution.
