### ISSUE TITLE
Update to rxdart 0.21

### ISSUE THREAD

**Issue by cosinus84** [lukepighetti/hydrated#9]
I tried to use the package but requires rxdart 0.20. I don't think I have something that can benefit from 0.21 but would be ok to update the package to 0.21.
Thanks

**Comment by lukepighetti** [comment]
Thanks for putting this on my radar. They had some breaking changes to BehaviorSubject and I haven't finished up migrating to 0.21. I will try to get this done before the end of the week.

**Comment by shinayser** [comment]
Any update on this issue?

**Comment by lukepighetti** [comment]
My apologies, I have been away from software for a week or so. Would really appreciate a PR on this.

**Comment by ccadieux** [comment]
PR: https://github.com/lukepighetti/hydrated/pull/10
